# Generated by Django 6.1.1 on 2026-09-06 06:08

import base.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenticTaskSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('prompt', models.TextField()),
                ('num_agents_requested', models.PositiveSmallIntegerField(default=3)),
                ('num_agents_spawned', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial failure'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('synthesized_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['orchestration_run', 'round_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prompt_fragment', models.TextField(help_text="Text appended/injected into the executor's prompt to induce this persona's behavior.")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutorAgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveSmallIntegerField()),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('missing_output', 'Missing output')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('execution_log', models.JSONField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_runs', to='base.agentictaskset')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_runs', to='base.persona')),
            ],
            options={
                'ordering': ['task_set', 'index'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.screenshot_upload_path)),
                ('step_number', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('executor_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='base.executoragentrun')),
            ],
            options={
                'ordering': ['executor_run', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_inquiry', models.TextField()),
                ('target_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('final_report', models.TextField(blank=True)),
                ('model_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentictaskset',
            name='orchestration_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sets', to='base.orchestrationrun'),
        ),
        migrations.AddConstraint(
            model_name='executoragentrun',
            constraint=models.UniqueConstraint(fields=('task_set', 'index'), name='unique_index_per_task_set'),
        ),
    ]
