# Generated by Django 6.1.1 on 2026-09-10 00:12

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_agentictaskset_input_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executorscreenshot',
            name='image',
            field=models.ImageField(max_length=255, upload_to=base.models.screenshot_upload_path),
        ),
    ]
